#######################################################
# 
# core_name_general_controller.py
# Python implementation of the Class CoreNameGeneralController
# Generated by Enterprise Architect
# Created on:      16-Dec-2022 10:56:05 AM
# Original author: Giu Platania
# 
#######################################################
from Catalog.Implementation.Libraries.Digitalpy.digitalpy.Async.routing.controller import Controller

class ComponentManagementGeneralController(Controller):
# default constructor  def __init__(self):  

    def __init__(Request, Response, ActionMapper, Configuration):
        pass

    def execute( = None):
        pass

    def serialize_component_management():
        """this is the general method used to serialize the component to a given format
        """
        pass
        
	def start_component():
		"""Starts a specific component"""
    	pass
    	
	def stop_component():
		"""Stops a specific component"""
    	pass
    	
	def restart_component():
		"""Restarts a specific component"""
    	pass
    	
	def component_discovery():
		"""discover all the installed components"""
    	pass
    	
	def register_component():
		"""Registers a new component in the system"""
    	pass
    	
	def list_components():
		"""Lists all the registered components in the system"""
    	pass
    	
	def get_component_info():
		"""Retrieves information about a specific component"""
    	pass
    	
	def update_component():
		"""Updates the information of an existing component"""
    	pass
    	
