#######################################################
# 
# core_name_general_controller.py
# Python implementation of the Class CoreNameGeneralController
# Generated by Enterprise Architect
# Created on:      16-Dec-2022 10:56:05 AM
# Original author: Giu Platania
# 
#######################################################
from Catalog.Implementation.Libraries.Digitalpy.digitalpy.Async.routing.controller import Controller

class PersistenceGeneralController(Controller):
# default constructor  def __init__(self):  

    def __init__(Request, Response, ActionMapper, Configuration):
        pass

    def execute( = None):
        pass

    def serialize_persistence():
        """this is the general method used to serialize the component to a given format
        """
        pass
        
	def db_support_activate_saving_cot_into_db():
		"""core"""
    	pass
    	
	def db_multiple_support():
		"""Support for any DB"""
    	pass
    	
	def db_support_mysql():
		"""Experimental"""
    	pass
    	
	def cot_record_in_db():
		"""record all the traffic in the Database"""
    	pass
    	
	def db_support_sql_lite():
		"""core"""
    	pass
    	
