#######################################################
# 
# core_name_general_controller.py
# Python implementation of the Class CoreNameGeneralController
# Generated by Enterprise Architect
# Created on:      16-Dec-2022 10:56:05 AM
# Original author: Giu Platania
# 
#######################################################
from Catalog.Implementation.Libraries.Digitalpy.digitalpy.Async.routing.controller import Controller

class DigiPyConfigurationGeneralController(Controller):
# default constructor  def __init__(self):  

    def __init__(Request, Response, ActionMapper, Configuration):
        pass

    def execute( = None):
        pass

    def serialize_digipy_configuration():
        """this is the general method used to serialize the component to a given format
        """
        pass
        
	def configure_dp_ip():
		"""Configure the IP of DP dynamically"""
		pass
 
	def web_ui_manage_services():
		"""the services can be turned on and off and a port can be assigned to the service."""
		pass
 
	def installation_wizard():
		""" guides the user trough the installation process"""
		pass
 
	def configure_set_port():
		"""Ability to set port dynamically"""
		pass
 
	def configuration_wizard():
		"""starts a wizard to create a YAML configuration"""
		pass
 
