#######################################################
# 
# fileFacade.py
# Python implementation of the Class fileFacade
# Generated by Enterprise Architect
# Created on:      28-Dec-2022 1:11:18 PM
# Original author: Giu Platania
# 
#######################################################


from typing import List

class FileSystemFacade:
    def create_file(self, file_path: str, data: str) -> bool:
        """Create a new file with the given data at the specified file path."""
        pass

    def read_file(self, file_path: str) -> str:
        """Read the data from the file at the given file path."""
        pass

    def update_file(self, file_path: str, data: str) -> bool:
        """Update the data in the file at the given file path with the new data."""
        pass

    def delete_file(self, file_path: str) -> bool:
        """Delete the file at the given file path."""
        pass

    def list_files(self, directory_path: str) -> List[str]:
        """List the names of all files in the given directory."""
        pass