#######################################################
# 
# Function.py
# Python implementation of the Class Function
# Generated by Enterprise Architect
# Created on:      27-Dec-2022 9:21:52 AM
# Original author: Giu Platania
# 
#######################################################
from . import Root

class Function:
    """the class function contains the description of a function and his relationship
    to a certain component.
    """
    def __init__(self, component_name, group_permissions, name, uid):
        self.component_name = component_name
        self.group_permissions = group_permissions
        self.name = name
        self.uid = uid

    def get_component_name(self):
        return self.component_name

    def set_component_name(self, component_name):
        self.component_name = component_name

    def get_group_permissions(self):
        return self.group_permissions

    def set_group_permissions(self, group_permissions):
        self.group_permissions = group_permissions

    def get_name(self):
        return self.name

    def set_name(self, name):
        self.name = name

    def get_uid(self):
        return self.uid

    def set_uid(self, uid):
        self.uid = uid