#######################################################
# 
# Root.py
# Python implementation of the Class Root
# Generated by Enterprise Architect
# Created on:      27-Dec-2022 9:11:27 AM
# Original author: natha
# 
#######################################################


class Root:

	def __init__(self, name, uid):  
		self.Name = name
		self.UID = uid