#######################################################
# 
# SystemUser.py
# Python implementation of the Class SystemUser
# Generated by Enterprise Architect
# Created on:      27-Dec-2022 9:08:59 AM
# Original author: Giu
# 
#######################################################
import Root
import Group

class SystemUser(Root):
    def __init__(self, name, group, token, password, certs, uid):
        self.name = name
        self.group = group
        self.token = token
        self.password = password
        self.certs = certs
        self.uid = uid 

    def get_certs():
        pass

    def get_group():
        pass

    def get_password():
        pass

    def get_uid():
        pass