#######################################################
# 
# ComponentNameDomain.py
# Python implementation of the Class ComponentNameDomain
# Generated by Enterprise Architect
# Created on:      28-Dec-2022 10:14:13 AM
# Original author: Giu Platania
# 
#######################################################


class ComponentNameDomain(Domain):
    """This class is to be used for all interactions with the ComponentName domain
    model. This class exposes and handles all domain model functions.
    """
# default constructor  def __init__(self):  

    def __init__():
        pass