#######################################################
# 
# ComponentNameActionMapper.py
# Python implementation of the Class ComponentNameActionMapper
# Generated by Enterprise Architect
# Created on:      28-Dec-2022 10:14:12 AM
# Original author: Giu Platania
# 
#######################################################
from Catalog.Implementation.Libraries.Digitalpy.digitalpy Async.routing.impl.default_action_mapper import DefaultActionMapper

class ComponentNameActionMapper(DefaultActionMapper):
    """This is the ComponentName component action mapper.  Each component must have
    its own action mapper to be loaded with the internal action mapping
    configuration and to be used by the facade for internal routing.
    """
# default constructor  def __init__(self):  

    pass