#######################################################
# 
# NetworkPersistence.py
# Python implementation of the Class NetworkPersistence
# Generated by Enterprise Architect
# Created on:      28-Dec-2022 10:14:20 AM
# Original author: Giu Platania
# 
#######################################################
from Catalog.Implementation.Libraries.Digitalpy.digitalpy Async.routing.controller import Controller

class NetworkPersistence(Controller):
    """this class is responsible for managing saved components
    """
# default constructor  def __init__(self):  

    def __init__():
        pass

    def _sync_persistence():
        """synchronize the current, in-memory state, with the persistence
        """
        pass

    def _update_persistence():
        """update the persistence with the in memory state
        """
        pass

    def delete_component():
        """this method removes the specified component from the list of components  Args:
          component (Event): the Component delete model object
        """
        pass

    def execute( = None):
        pass

    def get_all_components():
        """this method is gets all the saved component objects and returns them as a list
        of component objects
        """
        pass

    def save_component():
        """this method adds a new component to the list of components  Args:
        model_object (Event): the new Component model object
        """
        pass