#######################################################
# 
# NetworkRulesController.py
# Python implementation of the Class NetworkRulesController
# Generated by Enterprise Architect
# Created on:      28-Dec-2022 10:14:22 AM
# Original author: Giu Platania
# 
#######################################################
from Catalog.Implementation.Libraries.Digitalpy.digitalpy Async.logic.impl.default_business_rule_controller import DefaultBusinessRuleController

class NetworkRulesController(DefaultBusinessRuleController):
# default constructor  def __init__(self):  

    def __init__():
        pass

    def execute( = None):
        pass

    def parse_component_name():
        """Creates the model object outline and passes it to the parser to fill the model
        object with the xml data
        """
        pass