#######################################################
# 
# NetworkSenderController.py
# Python implementation of the Class NetworkSenderController
# Generated by Enterprise Architect
# Created on:      28-Dec-2022 10:14:23 AM
# Original author: Giu Platania
# 
#######################################################
from Core.Network.domain.DigitalPy\Core\Network\domain\Network import Network
from Catalog.Implementation.Libraries.Digitalpy.digitalpy Async.routing.controller import Controller

class NetworkSenderController(Controller):
    """this class is responsible for transmitting components, however it is not used
    as all routing should be going through the main
    """
# default constructor  def __init__(self):  

    def __init__(Request, Response, ActionMapper, Configuration):
        """internal action mapper is used so that the serialize_component  controller can
        be reached
        """
        pass

    def broadcast_component_name(Network):
        """this method will broadcast the component
        """
        pass

    def execute( = None):
        pass