#######################################################
# 
# core_name_general_controller.py
# Python implementation of the Class CoreNameGeneralController
# Generated by Enterprise Architect
# Created on:      16-Dec-2022 10:56:05 AM
# Original author: Giu Platania
# 
#######################################################
from Catalog.Implementation.Libraries.Digitalpy.digitalpy.Async.routing.controller import Controller

class NetworkGeneralController(Controller):
# default constructor  def __init__(self):  

    def __init__(Request, Response, ActionMapper, Configuration):
        pass

    def execute( = None):
        pass

    def serialize_network():
        """this is the general method used to serialize the component to a given format
        """
        pass
        
	def ftp_connect():
		"""Connect to the FTP server"""
		pass
 
	def ftp_download():
		"""send a file over FTP to a connected client for Download"""
		pass
 
	def ftp_upload():
		"""receive a file from a connected client"""
		pass
 
