#######################################################
# 
# core_name_general_controller.py
# Python implementation of the Class CoreNameGeneralController
# Generated by Enterprise Architect
# Created on:      16-Dec-2022 10:56:05 AM
# Original author: Giu Platania
# 
#######################################################
from Catalog.Implementation.Libraries.Digitalpy.digitalpy.Async.routing.controller import Controller

class SerializationGeneralController(Controller):
# default constructor  def __init__(self):  

    def __init__(Request, Response, ActionMapper, Configuration):
        pass

    def execute( = None):
        pass

    def serialize_serialization():
        """this is the general method used to serialize the component to a given format
        """
        pass
        
	def deserialize():
		"""Deserializes a byte stream into an object"""
		pass
 
	def serialize_to_file():
		"""Serializes an object into a file"""
		pass
 
	def serialize():
		"""Serializes an object into a byte stream"""
		pass
 
	def domain_to_xml_parsing():
		"""convert Domain model to XML string"""
		pass
 
	def xml_to_domain_parsing():
		"""convert XML string to Domain model"""
		pass
 
	def domain_to_json_parsing():
		"""convert Domain model object to JSON string"""
		pass
 
	def domain_to_protobuf_parsing():
		"""convert Domain model object to protobuf"""
		pass
 
	def deserialize_from_file():
		"""Deserializes a file into an object"""
		pass
 
