#######################################################
# 
# ComponentPropertyVariables.py
# Python implementation of the Class ComponentPropertyVariables
# Generated by Enterprise Architect
# Created on:      28-Dec-2022 10:14:15 AM
# Original author: Giu Platania
# 
#######################################################


class ComponentPropertyVariables:
# default constructor  def __init__(self):  

    %WRAP_COMMENT(linkAttNotes, genOptWrapComment, """"", "# ")%
    self.COMPONENTPROPERTYATTRIBUTE = COMPONENTPROPERTYATTRIBUTE

    def __init__():
        pass