#######################################################
# 
# ComponentNameRules.py
# Python implementation of the Class ComponentNameRules
# Generated by Enterprise Architect
# Created on:      28-Dec-2022 10:14:14 AM
# Original author: Giu Platania
# 
#######################################################


class ComponentNameRules:
# default constructor  def __init__(self):  

    pass