#######################################################
# 
# componentproperty.py
# Python implementation of the Class componentproperty
# Generated by Enterprise Architect
# Created on:      28-Dec-2022 10:14:14 AM
# Original author: Giu Platania
# 
#######################################################


class componentproperty(CoTNode):
# default constructor  def __init__(self):  

    def __init__():
        pass

    @CoTProperty
    def componentpropertyattribute():
        pass

    @componentpropertyattribute.setter
    def componentpropertyattribute( = None):
        pass