#######################################################
# 
# Network.py
# Python implementation of the Class Network
# Generated by Enterprise Architect
# Created on:      28-Dec-2022 10:14:16 AM
# Original author: Giu Platania
# 
#######################################################


class Network(CoTNode):
# default constructor  def __init__(self):  

    def __init__(Configuration):
        pass

    @CoTProperty
    def detail():
        pass

    @detail.setter
    def detail( = None):
        pass

    @CoTProperty
    def how():
        pass

    @how.setter
    def how( = 0):
        pass

    @CoTProperty
    def point():
        pass

    @point.setter
    def point( = None):
        pass

    @CoTProperty
    def stale():
        pass

    @stale.setter
    def stale( = None,  = 60):
        pass

    @CoTProperty
    def start():
        pass

    @start.setter
    def start( = 0):
        pass

    @CoTProperty
    def time():
        pass

    @time.setter
    def time( = 0):
        pass

    @CoTProperty
    def type():
        pass

    @type.setter
    def type( = 0):
        pass

    @CoTProperty
    def uid():
        pass

    @uid.setter
    def uid():
        pass

    @CoTProperty
    def version():
        pass

    @version.setter
    def version():
        pass