#######################################################
# 
# core_name_general_controller.py
# Python implementation of the Class CoreNameGeneralController
# Generated by Enterprise Architect
# Created on:      16-Dec-2022 10:56:05 AM
# Original author: Giu Platania
# 
#######################################################
from Catalog.Implementation.Libraries.Digitalpy.digitalpy.Async.routing.controller import Controller

class DataPackageGeneralController(Controller):
# default constructor  def __init__(self):  

    def __init__(Request, Response, ActionMapper, Configuration):
        pass

    def execute( = None):
        pass

    def serialize_data_package():
        """this is the general method used to serialize the component to a given format
        """
        pass
        
	def data_package__download_file_https():
		"""download one file from the server via https"""
    	pass
    	
	def data_package__upload_file_https():
		"""upload one file to the server via https"""
    	pass
    	
	def data_package__download_file_http():
		"""download one file from the server via http"""
    	pass
    	
	def replay_hystory():
		"""Stream a stored set of COT's time period to the client """
    	pass
    	
	def data_package___file_list_http():
		"""get a list of files on the server"""
    	pass
    	
	def data_package__generate_show_qr_code():
		""""""
    	pass
    	
	def data_package__upload_file():
		"""Upload a DP from the UI"""
    	pass
    	
	def data_package__delete_file():
		"""Delete a file from the server"""
    	pass
    	
	def data_package__download_file():
		"""download a file from the server"""
    	pass
    	
	def data_package__is_private():
		"""This function allows you to hide data packages from ATAK / WinTAK users simply by checking the box in this column. All private data packages, exchanged between clients, are listed as private"""
    	pass
    	
	def data_package__upload_file_http():
		"""upload one file to the server via http"""
    	pass
    	
	def data_package__file_list():
		"""provide a list of files on the server"""
    	pass
    	
	def broadcast_data_package_to_all_users():
		"""Send certain Data Packages (DP) from the User Interface to all the connected users.  """
    	pass
    	
	def excheck__join_existing_checklist():
		"""join the user to a started set of tasks"""
    	pass
    	
	def enrollment():
		"""Enroll to FTS, provisioning ATAK devices through Device Profiles.  """
    	pass
    	
	def data_package__file_list_https():
		"""get a list of files on the server via https"""
    	pass
    	
