#######################################################
# 
# core_name_general_controller.py
# Python implementation of the Class CoreNameGeneralController
# Generated by Enterprise Architect
# Created on:      16-Dec-2022 10:56:05 AM
# Original author: Giu Platania
# 
#######################################################
from Catalog.Implementation.Libraries.Digitalpy.digitalpy.Async.routing.controller import Controller

class TelemetryGeneralController(Controller):
# default constructor  def __init__(self):  

    def __init__(Request, Response, ActionMapper, Configuration):
        pass

    def execute( = None):
        pass

    def serialize_telemetry():
        """this is the general method used to serialize the component to a given format
        """
        pass
        
	def get_telemetry_config():
		"""Retrieve telemetry configuration"""
    	pass
    	
	def log():
		"""send to the UI relevant logs"""
    	pass
    	
	def get_telemetry_data():
		"""Retrieve telemetry data for a specific time period"""
    	pass
    	
	def set_telemetry_data():
		"""Store telemetry data in the system"""
    	pass
    	
	def get_telemetry_alarms():
		"""Retrieve telemetry alarms"""
    	pass
    	
	def dashboard__logs():
		"""display errors"""
    	pass
    	
	def telemetry():
		"""manage telemetry data (metrics, logs, and traces) to facilitate the analysys of the component performance and behavior."""
    	pass
    	
	def set_telemetry_config():
		"""Update telemetry configuration"""
    	pass
    	
	def metrics():
		"""live business metrics used to have insights about the behavior of components. e.g. usage of a REST API"""
    	pass
    	
	def telemetry():
		"""gather telemetry information from the different parts of the system and provides access to authorized third parties.
		2 parts one is aggregation and the other production
		"""
    	pass
    	
	def dashboard__runtime_and_connected_clients():
		"""provide informations regarding connected clients"""
    	pass
    	
