#######################################################
# 
# core_name_general_controller.py
# Python implementation of the Class CoreNameGeneralController
# Generated by Enterprise Architect
# Created on:      16-Dec-2022 10:56:05 AM
# Original author: Giu Platania
# 
#######################################################
from Catalog.Implementation.Libraries.Digitalpy.digitalpy.Async.routing.controller import Controller

class COTManagementGeneralController(Controller):
# default constructor  def __init__(self):  

    def __init__(Request, Response, ActionMapper, Configuration):
        pass

    def execute( = None):
        pass

    def serialize_cot_management():
        """this is the general method used to serialize the component to a given format
        """
        pass
        
	def build_drop_point_object():
		"""instantiate domain object with drop point structure"""
    	pass
    	
	def cot__share_privately():
		"""Send COT to specific client"""
    	pass
    	
	def cot_record_in_db():
		"""record all the traffic in the Database"""
    	pass
    	
	def cot__broadcast():
		"""send the CoT to all connected clients"""
    	pass
    	
	def medevac__receive():
		"""Receive a Medical Evaluation send by another EUD trough the server"""
    	pass
    	
	def web_ui_manage_presence():
		"""Using this function, the user can create a custom team member (friendly Dot) on the ATAK map, who will however appear like a real TAK user."""
    	pass
    	
	def medevac__send():
		"""send a MedEvac form to another EUD connected to the server"""
    	pass
    	
