#######################################################
# 
# core_name_general_controller.py
# Python implementation of the Class CoreNameGeneralController
# Generated by Enterprise Architect
# Created on:      16-Dec-2022 10:56:05 AM
# Original author: Giu Platania
# 
#######################################################
from Catalog.Implementation.Libraries.Digitalpy.digitalpy.Async.routing.controller import Controller

class UtilGeneralController(Controller):
# default constructor  def __init__(self):  

    def __init__(Request, Response, ActionMapper, Configuration):
        pass

    def execute( = None):
        pass

    def serialize_util():
        """this is the general method used to serialize the component to a given format
        """
        pass
        
	def about():
		"""Display a list of contributors"""
		pass
 
	def web_map_search_cot():
		"""search a COT by Name"""
		pass
 
	def protobuf_to_domain_parsing():
		"""convert protobuf object to Domain model"""
		pass
 
	def json_to_domain_parsing():
		"""convert JSON string to Domain model"""
		pass
 
	def presense_update():
		"""Send updates to server to show the user is online"""
		pass
 
	def web_map_measure_distances():
		"""measure the distance between 2 points"""
		pass
 
	def presence_connect():
		"""Connect to server and share presense"""
		pass
 
	def data_package_generate_show_qr_code():
		""""""
		pass
 
	def send_welcome_message():
		"""Send a message as soon the user connects"""
		pass
 
	def rest_api_push_kml():
		"""allow the creation on all connected clients of structured information"""
		pass
 
	def presence_delete():
		"""Delete a user point from all connected devices to show user is offline"""
		pass
 
	def asci_welcome():
		"""display a welcome message for console"""
		pass
 
