#######################################################
# 
# GroupPermissions.py
# Python implementation of the Class GroupPermissions
# Generated by Enterprise Architect
# Created on:      27-Dec-2022 9:20:56 AM
# Original author: giu.platania
# 
#######################################################
import Root
import Function

class GroupPermissions(Root):
  def __init__(self, functions, group, uid, is_active):
        self.functions = functions
        self.group = group
        self.uid = uid
        self.is_active = is_active
